version: '2'

services:
    sfa:
        build:
            context: .
            args:
                - http_proxy=${http_proxy}
                - https_proxy=${https_proxy}
                - no_proxy=${no_proxy}
        ports:
            - "8000:8000"
        environment:
            - API_KEY=myapikey
            - UPDATE_PROXY=${http_proxy}
        restart: always
        #mem_reservation: '512m'
        #memswap_limit: '1g'
        #mem_limit: '1g'
        #cpuset: '1'
        #logging:
        #    driver: "syslog"
        #    options:
        #        syslog-address: "tcp://172.17.0.1:514"
        #        tag: "docker_{{.ImageName}}_{{.Name}}"
        #curl -k  -F 'file=@/home/lionel/malwares/calc.xll' -H "x-api-key: mykeyapi" https://127.0.0.1:8000/api/sfa_check_file
        #return json with "risk_score"
